"""
UMC消融实验简化配置文件
用于快速运行消融实验
"""

class UMCAblationParam:
    """UMC消融实验参数配置"""
    
    def __init__(self, experiment_name, args):
        self.experiment_name = experiment_name
        self.hyper_param = self._get_hyper_parameters(args)

    def _get_hyper_parameters(self, args):
        """获取消融实验的超参数"""
        
        # 基础配置
        base_config = {
            'pretrained_bert_model': 'uncased_L-12_H-768_A-12',
            'pretrain_batch_size': 64,  # 减小batch size用于快速实验
            'train_batch_size': 64,
            'eval_batch_size': 64,
            'test_batch_size': 64,
            'num_pretrain_epochs': 20,  # 减少预训练轮数
            'num_train_epochs': 30,     # 减少训练轮数
            'pretrain': [True],
            'aligned_method': 'ctc',
            'need_aligned': False,
            'freeze_pretrain_bert_parameters': [True],
            'freeze_train_bert_parameters': [True],
            'pretrain_temperature': [0.2],
            'train_temperature_sup': [1.4],
            'train_temperature_unsup': [1],
            'activation': 'tanh',
            'lr_pre': 2e-5,
            'lr': [3e-4],
            'weight_decay': 0.01,
            'feat_dim': 768,
            'hidden_size': 768,
            'grad_clip': -1.0,
            'warmup_proportion': 0.1,
            'hidden_dropout_prob': 0.1,
            'weight': 1.0,
            'loss_mode': 'rdrop',
            'base_dim': 256,
            'nheads': 8,
            'attn_dropout': 0.1,
            'relu_dropout': 0.1,
            'embed_dropout': 0.1,
            'res_dropout': 0.0,
            'attn_mask': True,
            'encoder_layers_1': 1,
            'fusion_act': 'tanh',
            
            # 数据集特定参数
            'text_feat_dim': 768,
            'video_feat_dim': 256,
            'audio_feat_dim': 768,
            
            # 损失权重
            'clustering_weight': 1.0,
            'contrastive_weight': 0.5,
            'compactness_weight': 0.3,
            'separation_weight': 0.2,
            'contrastive_temperature': 0.07,
        }
        
        # 根据实验名称添加特定配置
        experiment_configs = self._get_experiment_specific_configs()
        
        if self.experiment_name in experiment_configs:
            base_config.update(experiment_configs[self.experiment_name])
        
        return base_config
    
    def _get_experiment_specific_configs(self):
        """获取实验特定配置"""
        return {
            # ==================== ConFEDE消融实验 ====================
            
            'baseline_traditional': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'confede_only': {
                'enable_video_dual': True,
                'enable_audio_dual': True,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'text_guided_only': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': True,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'gated_fusion_only': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': True,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'full_confede': {
                'enable_video_dual': True,
                'enable_audio_dual': True,
                'enable_text_guided_attention': True,
                'enable_self_attention': True,
                'self_attention_layers': 2,
                'enable_gated_fusion': True,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            # ==================== 渐进策略消融实验 ====================
            
            'fixed_strategy': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'enable_enhanced_loss': False,
                'enable_kmeans_plus': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'progressive_only': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': True,
                'enable_enhanced_loss': False,
                'enable_kmeans_plus': False,
                'max_threshold': 0.5,
                'min_threshold': 0.05,
                'performance_window': 3,
                'patience': 5,
            },
            
            'enhanced_loss_only': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': False,
                'enable_enhanced_loss': True,
                'enable_kmeans_plus': False,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': True,
                'enable_compactness_loss': True,
                'enable_separation_loss': True,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'full_progressive': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': True,
                'enable_enhanced_loss': True,
                'enable_kmeans_plus': True,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': True,
                'enable_compactness_loss': True,
                'enable_separation_loss': True,
                'max_threshold': 0.5,
                'min_threshold': 0.05,
                'performance_window': 3,
                'patience': 5,
            },
            
            # ==================== 架构消融实验 ====================
            
            'standard_architecture': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'use_clustering_projector': False,
                'use_clustering_fusion': False,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'clustering_projector_only': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'use_clustering_projector': True,
                'use_clustering_fusion': False,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'full_optimized_architecture': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'use_clustering_projector': True,
                'use_clustering_fusion': True,
                'use_attention_pooling': True,
                'use_layer_norm': True,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            # ==================== 协同效果实验 ====================
            
            'only_confede': {
                'enable_video_dual': True,
                'enable_audio_dual': True,
                'enable_text_guided_attention': True,
                'enable_self_attention': True,
                'self_attention_layers': 2,
                'enable_gated_fusion': True,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'only_progressive': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': True,
                'enable_enhanced_loss': True,
                'enable_kmeans_plus': True,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': True,
                'enable_compactness_loss': True,
                'enable_separation_loss': True,
                'max_threshold': 0.5,
                'min_threshold': 0.05,
                'performance_window': 3,
                'patience': 5,
            },
            
            'only_architecture': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'use_clustering_projector': True,
                'use_clustering_fusion': True,
                'use_attention_pooling': True,
                'use_layer_norm': True,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'full_umc_model': {
                'enable_video_dual': True,
                'enable_audio_dual': True,
                'enable_text_guided_attention': True,
                'enable_self_attention': True,
                'self_attention_layers': 2,
                'enable_gated_fusion': True,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': True,
                'enable_enhanced_loss': True,
                'enable_kmeans_plus': True,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': True,
                'enable_compactness_loss': True,
                'enable_separation_loss': True,
                'max_threshold': 0.5,
                'min_threshold': 0.05,
                'performance_window': 3,
                'patience': 5,
                'use_clustering_projector': True,
                'use_clustering_fusion': True,
                'use_attention_pooling': True,
                'use_layer_norm': True,
            },
            
            # ==================== 创新点三：聚类优化架构消融实验 ====================
            
            'baseline_no_clustering': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'use_clustering_projector': False,
                'use_clustering_fusion': False,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'enable_clustering_loss': False,
                'enable_contrastive_loss': False,
                'enable_compactness_loss': False,
                'enable_separation_loss': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'clustering_projector_only': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': False,
                'use_clustering_projector': True,
                'use_clustering_fusion': False,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': False,
                'enable_compactness_loss': False,
                'enable_separation_loss': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'clustering_fusion_only': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': False,
                'use_clustering_projector': False,
                'use_clustering_fusion': True,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': False,
                'enable_compactness_loss': False,
                'enable_separation_loss': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'clustering_loss_only': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': False,
                'use_clustering_projector': False,
                'use_clustering_fusion': False,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': True,
                'enable_compactness_loss': True,
                'enable_separation_loss': True,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'no_clustering_loss': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': False,
                'enable_progressive_learning': False,
                'use_clustering_projector': False,
                'use_clustering_fusion': False,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'enable_clustering_loss': False,
                'enable_contrastive_loss': False,
                'enable_compactness_loss': False,
                'enable_separation_loss': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'clustering_projector_fusion': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': False,
                'use_clustering_projector': True,
                'use_clustering_fusion': True,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': False,
                'enable_compactness_loss': False,
                'enable_separation_loss': False,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'clustering_projector_loss': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': False,
                'use_clustering_projector': True,
                'use_clustering_fusion': False,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': True,
                'enable_compactness_loss': True,
                'enable_separation_loss': True,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'clustering_fusion_loss': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': False,
                'use_clustering_projector': False,
                'use_clustering_fusion': True,
                'use_attention_pooling': False,
                'use_layer_norm': False,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': True,
                'enable_compactness_loss': True,
                'enable_separation_loss': True,
                'thres': [0.25],
                'delta': [0.0],
            },
            
            'full_clustering_optimization': {
                'enable_video_dual': False,
                'enable_audio_dual': False,
                'enable_text_guided_attention': False,
                'enable_self_attention': False,
                'enable_gated_fusion': False,
                'enable_clustering_optimization': True,
                'enable_progressive_learning': False,
                'use_clustering_projector': True,
                'use_clustering_fusion': True,
                'use_attention_pooling': True,
                'use_layer_norm': True,
                'enable_clustering_loss': True,
                'enable_contrastive_loss': True,
                'enable_compactness_loss': True,
                'enable_separation_loss': True,
                'thres': [0.25],
                'delta': [0.0],
            },
        }
